<?php

namespace Softspring\CoreBundle\DependencyInjection\Compiler;

use Softspring\Component\DoctrineTargetEntityResolver\DependencyInjection\Compiler\AbstractResolveDoctrineTargetEntityPass as ComponentAbstractResolveDoctrineTargetEntityPass;

/**
 * @deprecated Use Softspring\Component\DoctrineTargetEntityResolver\DependencyInjection\Compiler/AbstractResolveDoctrineTargetEntityPass
 */
abstract class AbstractResolveDoctrineTargetEntityPass extends ComponentAbstractResolveDoctrineTargetEntityPass
{
}
